TokTok/ci-tools

.travis.yml, stack.yaml
So it can be used in the c-toxcore build for style checking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/1)
=> Add tokstyle to the hs-tools build.

stack.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/4)
=> Format yaml files according to yamllint's requirements.

.travis.yml, stack.yaml
This gives us GHC 8.8.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/5)
=> Update to the latest LTS version of haskell stack.

.travis.yml
dpl v2 (edge) seems to not upload files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/7)
=> Revert to "deployment" v1.

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/8)
=> Output the released tarball to the repo checkout dir.

bin/travis-haskell
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/15)
=> Fix typo: () is not how you call functions in bash.

.travis.yml, README.md, bin/travis-haskell
Also, renamed the repo to ci-tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/16)
=> Add support for downloading other tools such as tokstyle.

bin/travis-haskell
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/19)
=> Use actual json parser instead of grep to get release tag name.

.github/settings.yml, bin/stack-haddock-upload
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/20)
=> Add stack-haddock-upload script to upload docs to hackage.

.github/settings.yml, bin/check_release, stack.yaml
We put it here so it can be independently updated and shared across
repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/27)
=> feat: Add `check_release` script, used by other repos.

bin/hackage_upload
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/28)
=> feat: Add `hackage_upload` script used by Haskell GH actions.

bin/hackage_upload
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/29)
=> fix: Fix hackage upload URL for package candidates.

bin/check_release
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/31)
=> chore: Make path argument in check_release optional.

bin/check_release
Use the ast module instead to parse out the version number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/32)
=> fix: Don't evaluate BUILD.bazel.

workflows/check-release.yml, workflows/haskell/ci.yml, workflows/haskell/publish.yml
This allows sharing and centralised updating of workflows without lots of
PRs to all the Haskell repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/35)
=> feat: Add Haskell workflows that can be called from other repos.

.github/workflows/check-release.yml, .github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/38)
=> chore: Give workflows human readable names.

.github/workflows/haskell-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/39)
=> chore: Make cache key depend on ghc version.

.github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml
They don't end up making things more readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/40)
=> chore: Simplify workflow job names.

.github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/41)
=> chore: Add options to workflows to set the ghc version.

.github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml
This breaks cabal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/42)
=> chore: Don't restore from unversioned cache keys.

.github/workflows/haskell-ci.yml
8.10.7 doesn't exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/45)
=> chore: Downgrade ghc to 8.10.3.

.github/workflows/haskell-publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/46)
=> chore: Add secrets for hackage upload.

.github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/47)
=> chore: Force a cabal update before build.

bin/stylish-haskell-lhs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/49)
=> feat: Add support for dpkg-divert'ed stylish-haskell.

bin/stylish-haskell-lhs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/50)
=> feat: Support reading from stdin in stylish-haskell-lhs.

.github/workflows/haskell-publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/51)
=> chore: Push haskell CI docker images to dockerhub.

.github/workflows/haskell-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/53)
=> chore: Use docker image for haskell builds.

.github/workflows/haskell-ci.yml, .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/54)
=> chore: Use toxchat/haskell image.

.github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml
Not useful since everything is cached in the base image now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/55)
=> chore: Remove docker buildcache.

.github/workflows/haskell-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/56)
=> chore: Fix image reference.

.github/workflows/haskell-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/57)
=> chore: Use the github actions `container` setting.

.github/workflows/haskell-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/58)
=> chore: Temporary workaround: set HOME.

.github/workflows/haskell-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/59)
=> chore: Use toktok-stack:haskell instead of toxchat/haskell.

.github/workflows/haskell-ci.yml
Depends on https://github.com/TokTok/toktok-stack/pull/375.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/61)
=> chore: Run tests and build source package for haskell stack builds.

bin/check_release
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/63)
=> chore: Print API response for debugging.

.gitignore, bin/check_release
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/64)
=> fix: Ignore empty response from github api.

bin/check_release
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/65)
=> fix: Fix bzl file parser.

.github/workflows/common-ci.yml, stack.yaml
Also upgrade to buildifier 5.0.1.
Also removed unused stack.yaml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/66)
=> chore: Try to download buildifier 3 times before giving up.

.github/workflows/common-ci.yml
They changed their format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/68)
=> chore: Fix version tag for buildifier.

.github/workflows/haskell-publish.yml
Also, it moved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/69)
=> chore: Update setup-haskell action to latest version.

.github/workflows/check-release.yml, .github/workflows/common-ci.yml, .github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/73)
=> chore: Update github actions.

.github/workflows/ci.yml, .github/workflows/common-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/74)
=> chore: Add restyled workflow in common CI actions.

.github/workflows/check-release.yml, .github/workflows/checks.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/76)
=> feat: Add release drafter common github action.

.github/workflows/checks.yml, .github/workflows/common-ci.yml
See https://github.com/restyled-io/actions/issues/46#issuecomment-2462766875
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/77)
=> feat: Upload restyled diff as artifact.

.github/workflows/common-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/79)
=> fix: It's `git-patch` instead of `patch`.

.github/workflows/common-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/80)
=> fix: Terminate restyled action with error if a patch exists.

bin/check_release
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/84)
=> fix: Actually handle all the cases of versions being available or not.

bin/check_release
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/85)
=> fix: Respect the local_required bool.

.github/workflows/check-release.yml, .github/workflows/common-ci.yml, .github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml, .github/workflows/release-drafter.yml
Also fixed ubuntu runner to 22.04 to suppress warnings in CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/86)
=> chore: Update buildifier to v7.3.1.

.github/workflows/release-soon.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/89)
=> feat: Add a release-soon workflow to check if we should release soon.

.github/workflows/netlify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/90)
=> feat: Add netlify deploy workflow.

scripts/install_apple_cert.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/91)
=> feat: Add install_apple_cert tool to ci-tools scripts.

.github/workflows/deploy-artifact.yml, tools/rename_artifact.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/94)
=> feat: Add support for multi-file generic artifacts.

.github/workflows/deploy-artifact.yml, tools/artifact_rename.py, tools/artifact_sha256.py
Previously we needed a single glob. Now we can have multiple globs. "source" and "versioned" need to agree for each glob (space-separated).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/95)
=> feat: Add support for multiple distinct artifacts.

.github/workflows/draft.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/98)
=> test: Add a netlify release test workflow job.

.github/workflows/deploy-macos.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/99)
=> fix: Don't try to upload release artifacts on master builds.

.github/workflows/deploy-artifact.yml, .netlify/state.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/100)
=> fix: Checkout ci-tools into the correct directory.

.github/workflows/deploy-appimage.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/102)
=> fix: Fix screenshotting in appimage build.

.github/ISSUE_TEMPLATE/release.yaml, .github/workflows/draft.yml, .github/workflows/release.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/103)
=> chore: Add release issue template and workflow.

.github/workflows/draft.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/104)
=> chore: Fix release drafter runs aborting each other across PRs.

.github/workflows/release.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/105)
=> chore: Limit concurrency by release tracking issue number.

.github/workflows/release-deploy.yml
Repos have a .gitignore there to avoid committing it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/106)
=> fix: Checkout ci-tools into third_party.

tools/lib/github.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/107)
=> fix: Clear the correct cache on `clear_cache`.

tools/create_release.py
So we don't start a new version at the end of a release candidate.
Also, don't close the milestone on release candidates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/108)
=> fix: Use the version from the tracking issue if available.

tools/validate_pr.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/110)
=> fix: Be less qtox-specific.

tools/create_release.py, tools/verify_release_assets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/109)
=> feat: Show number of release assets verified in the log.

tools/verify_release_assets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/111)
=> fix: Verify all assets (except signatures and hashes).

tools/update_flathub_descriptor_dependencies.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/114)
=> fix: Better detect the project's self-name.

tools/update_flathub_descriptor_dependencies.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/115)
=> fix: Fix self-name detection for real now.

.github/workflows/release-deploy.yml, tools/lib/github.py
Creating PRs using toktok-releaser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/118)
=> fix: Forcibly trigger CI on automation pull requests.

.github/workflows/release.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/119)
=> chore: Add required secret to release workflow.

.reviewable/completion.js, .reviewable/settings.yaml
Enforcing 2 reviewers for bot PRs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/121)
=> chore: Add reviewable config.

.reviewable/completion.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/122)
=> fix: Reviewable config was broken.

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/112)
=> chore: Add a mypy type check to CI.

.github/workflows/check-release.yml, .github/workflows/common-ci.yml, .github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml, .github/workflows/netlify.yml, .github/workflows/release-deploy.yml, .github/workflows/release-drafter.yml, .github/workflows/release-soon.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/120)
=> cleanup: Add names to all the workflows.

tools/update_changelog.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/124)
=> fix: Output a zero-length file when changelog is empty.

.github/workflows/release-soon.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/125)
=> fix: Don't run release-soon check on pushes, only pulls.

.github/workflows/release-soon.yml
That happens to be pull_request_target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/126)
=> fix: Run release-soon on everything except push.

tools/lib/changelog.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/131)
=> fix: Don't erase release candidate's release notes.

CHANGELOG.md
Prod release for ci-tools.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/132)
=> chore: Release v0.8.1

README.md, tools/update-versions.sh
Also add a version updater for the readme version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/137)
=> docs: Update readme to better reflect what this repo is.

.github/workflows/deploy-flatpak.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/135)
=> cleanup: Use ci-tools flatpak builder script.

.github/workflows/deploy-appimage.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/134)
=> cleanup: Use ci-tools appimage builder script.

.github/workflows/deploy-appimage.yml, .github/workflows/deploy-windows.yml, platform/android/cross-compile/build.sh
So we don't need copies in every repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/139)
=> cleanup: Use common debug keystore from ci-tools.

.github/workflows/deploy-appimage.yml, .github/workflows/deploy-windows.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/138)
=> cleanup: Use ci-tools windows builder script.

cmake/Installation.cmake, platform/flatpak/build.sh, platform/macos/createdmg, platform/windows/cross-compile/build.sh, platform/windows/generate-icon.sh
Also make sure the scripts are using the git root instead of ci-tools script dir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/140)
=> cleanup: Use ci-tools createdmg and gplv3.rtf.

.github/workflows/common-ci.yml, tools/create_release.py, tools/lib/git.py, tools/sign_tag.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/141)
=> feat: Add tag signature verification stage in release.

.github/workflows/common-ci.yml, tools/lib/git.py, tools/sign_tag.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/136)
=> feat: Add script for signing release tags.

CHANGELOG.md, CMakeLists.txt, README.md
Add @Green-Sky to trusted signers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/144)
=> chore: Release v0.8.2

tools/create_release.py, tools/lib/github.py, tools/sign_release_assets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/145)
=> fix: Assign issue to release milestone; support gpg args.

tools/circleci-bazel-test
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/147)
=> feat: Add a script to run bazel builds on circle ci.

.github/workflows/deploy-flatpak.yml, tools/create_release.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/148)
=> fix: milestone assignment for rc

tools/update_changelog.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/149)
=> fix: Use "now" as the time stamp for unreleased versions.

.circleci/config.yml, tools/circleci-bazel-test
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/150)
=> chore: Add bazel test on circleci.

tools/circleci-bazel-test
We don't need to run tests again on master pushes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/151)
=> perf: Don't run circleci stuff on anything other than PRs.

tools/create_release.py
This ensures we don't try to commit ci-tools to the repo being released.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/152)
=> fix: Add ci-tools to the .gitignore during release.

tools/create_release.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/153)
=> fix: Don't add third_party/.gitignore if it doesn't exist.

.github/workflows/deploy-android.yml, .github/workflows/deploy-macos.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/154)
=> fix: Correct the android apk artifact names.

.github/workflows/flutter.yml
To be used by btox and tokhub.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/155)
=> feat: Add a standardised flutter workflow.

.github/workflows/flutter-pages.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/156)
=> feat: Add a shared GitHub Pages workflow for flutter apps.

tools/create_release.py
We need to compare with whitespace-stripped lines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/157)
=> fix: Don't duplicate lines in .gitignore.

.github/workflows/flutter.yml, tools/lib/github.py, tools/update_goldens.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/158)
=> feat: Add script to update flutter golden images from test failures.

tools/translate.py, tools/update_goldens.py
E.g. " MB" and " px".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/160)
=> fix: Preserve leading spaces in automated translations.
