.travis.yml, stack.yaml
So we can use it from the spec repo and perhaps other repos where we want
to process documentation (markdown, latex, etc).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/2)
=> Add pandoc to the tools.

.gitignore, stack.yaml
See https://github.com/jaspervdj/stylish-haskell/pull/265. Without this,
stylish-haskell deletes many comments and is generally broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/9)
=> Update stylish-haskell to 0.11.

.travis.yml
This tool fails to install via stack on travis because an existing happy
is needed, so we just pre-compile it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/10)
=> Add `happy` to hs-tools.

bin/travis-haskell
The `&&` made it so it would error if the lhs of the conjunction failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/13)
=> Fix script error when sodium or toxcore are not needed.

bin/travis-haskell
We don't want to stay in the build directory after building
libsodium/toxcore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-tools/14)
=> Use pushd/popd to enter and leave build directories.

bin/hackage_upload
Without the `--fail` flag, curl will succeed on HTTP errors. We want to
fail the GH workflow if upload fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/30)
=> fix: Fail the hackage_upload script on upload failure.

bin/check_release
This happens on the first PR after a release when release-drafter hasn't
produced a new draft release yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/34)
=> fix: Disable release version check when there's no draft release.

.github/workflows/haskell-ci.yml
It doesn't actually care about the ghc version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/43)
=> chore: Allow stack build to recover caches from other ghc versions.

.github/workflows/haskell-ci.yml
`generic-arbitrary` doesn't compile yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/44)
=> chore: Downgrade ghc to 8.10.7.

.github/workflows/haskell-ci.yml
The `.cabal` files are updated whenever a new source file is added. We
don't want to make a whole new cache everytime we do that. We invalidate
the cache only when dependencies change, which generally means the BUILD
file also changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/ci-tools/48)
=> chore: Use BUILD.bazel instead of cabal file for cache keys.

.github/workflows/check-release.yml, .github/workflows/common-ci.yml, .github/workflows/haskell-ci.yml, .github/workflows/haskell-publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/67)
=> chore: Update GH action uses to their latest versions.

.github/workflows/haskell-publish.yml
The former is deprecated.
See https://github.com/haskell/actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/72)
=> chore: Migrate from haskell/actions/setup to haskell-actions/setup.

.github/workflows/common-ci.yml
These have their own checks. We don't need to recurse into submodules.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/75)
=> fix: Don't try to restyle submodules.

.github/workflows/common-ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/78)
=> fix: Don't abort the restyled workflow before uploading a patch.

bin/check_release
We don't use it, but this makes it so we don't throw an exception about not finding a version in the repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/82)
=> feat: Support toxic's version location.

bin/check_release
There's already a milestone check that ensures a milestone is set. Once it is set, we check that it's correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/83)
=> fix: Allow milestone to be empty.

.github/workflows/common-ci.yml
Also, curl doesn't actually work without GH token, so tell the user to download the zip, instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/87)
=> chore: Add hub-restyled link to restyled errors.

.github/workflows/common-ci.yml
Should fix "The checked out commit does not match the event PR's head. 20a741e0d90339ae3f2bca41326e73f8ca6389db !=
715caf13cf2906727bffe7c4b6e964455d1c6bc5. Weird things may happen."
E.g. https://github.com/TokTok/qTox/actions/runs/12591052375?pr=354
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/88)
=> fix: Check out the PR head instead of merge commit in restyled.

tools/artifact_rename.py
This allows globs in the artifact name without corresponding globs in the versioned artifact name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/96)
=> fix: Support original-only artifact file name globs.

tools/update-versions.sh, tools/update_flathub_descriptor_dependencies.py, tools/validate_pr.py
We can use tokens in ci-tools code, but not in the version update scripts in user repos.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/123)
=> fix(Security): Don't pass tokens to repo-local code.

.github/workflows/deploy-macos.yml
Instead of repo-local ones. These are the same in every repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/ci-tools/133)
=> cleanup: Use ci-tools macos build script.
